export const data =
    [
        {
            "firstName": "Rohan",
            "lastName": "Singh",
            "middleName": "Kumar",
            "email": "user2@example.com",
            "imageUrl": "https://cdn2.storyasset.link/ahe4PDZx74Sp9y9Q7TVXpdjdnqs2/Probus-ms-yeprffkqqo.png",
            "gender": "Male",
            "maritalStatus": "Single",
            "country": "India",
            "state": "Delhi",
            "city": "New Delhi",
            "pincode": "110001"
        },
        {
            "firstName": "Aisha",
            "lastName": "Kapoor",
            "middleName": "Priyanka",
            "email": "user3@example.com",
            "imageUrl": "https://cdn2.storyasset.link/ahe4PDZx74Sp9y9Q7TVXpdjdnqs2/Probus-ms-yeprffkqqo.png",
            "gender": "Female",
            "maritalStatus": "Married",
            "country": "India",
            "state": "Karnataka",
            "city": "Bangalore",
            "pincode": "560001"
        },
        {
            "firstName": "Amit",
            "lastName": "Sharma",
            "middleName": "Vikram",
            "email": "user4@example.com",
            "imageUrl": "https://cdn2.storyasset.link/ahe4PDZx74Sp9y9Q7TVXpdjdnqs2/Probus-ms-yeprffkqqo.png",
            "gender": "Male",
            "maritalStatus": "Divorced",
            "country": "India",
            "state": "Tamil Nadu",
            "city": "Chennai",
            "pincode": "600001"
        },
        {
            "firstName": "Kiara",
            "lastName": "Mehta",
            "middleName": "Anya",
            "email": "user5@example.com",
            "imageUrl": "https://cdn2.storyasset.link/ahe4PDZx74Sp9y9Q7TVXpdjdnqs2/Probus-ms-yeprffkqqo.png",
            "gender": "Female",
            "maritalStatus": "Single",
            "country": "India",
            "state": "Gujarat",
            "city": "Ahmedabad",
            "pincode": "380001"
        },
        {
            "firstName": "Raj",
            "lastName": "Patel",
            "middleName": "Jayesh",
            "email": "user6@example.com",
            "imageUrl": "https://cdn2.storyasset.link/ahe4PDZx74Sp9y9Q7TVXpdjdnqs2/Probus-ms-yeprffkqqo.png",
            "gender": "Male",
            "maritalStatus": "Married",
            "country": "India",
            "state": "Rajasthan",
            "city": "Jaipur",
            "pincode": "302001"
        },
        {
            "firstName": "Priya",
            "lastName": "Bose",
            "middleName": "Riya",
            "email": "user7@example.com",
            "imageUrl": "https://cdn2.storyasset.link/ahe4PDZx74Sp9y9Q7TVXpdjdnqs2/Probus-ms-yeprffkqqo.png",
            "gender": "Female",
            "maritalStatus": "Single",
            "country": "India",
            "state": "West Bengal",
            "city": "Kolkata",
            "pincode": "700001"
        },
        {
            "firstName": "Vikram",
            "lastName": "Das",
            "middleName": "Aditya",
            "email": "user8@example.com",
            "imageUrl": "https://cdn2.storyasset.link/ahe4PDZx74Sp9y9Q7TVXpdjdnqs2/Probus-ms-yeprffkqqo.png",
            "gender": "Male",
            "maritalStatus": "Married",
            "country": "India",
            "state": "Odisha",
            "city": "Bhubaneswar",
            "pincode": "751001"
        },
        {
            "firstName": "Priya",
            "lastName": "Desai",
            "middleName": "Kiran",
            "email": "user1@example.com",
            "imageUrl": "https://cdn2.storyasset.link/ahe4PDZx74Sp9y9Q7TVXpdjdnqs2/Probus-ms-yeprffkqqo.png",
            "gender": "Female",
            "maritalStatus": "Married",
            "country": "India",
            "state": "Maharashtra",
            "city": "Mumbai",
            "pincode": "400001"
        }
    ]

// { position: 1, name: 'Hydrogen', weight: 1.0079, symbol: 'H' },
// { position: 2, name: 'Helium', weight: 4.0026, symbol: 'He' },
// { position: 3, name: 'Lithium', weight: 6.941, symbol: 'Li' },
// { position: 4, name: 'Beryllium', weight: 9.0122, symbol: 'Be' },
// { position: 5, name: 'Boron', weight: 10.811, symbol: 'B' },
// { position: 6, name: 'Carbon', weight: 12.0107, symbol: 'C' },
// { position: 7, name: 'Nitrogen', weight: 14.0067, symbol: 'N' },
// { position: 8, name: 'Oxygen', weight: 15.9994, symbol: 'O' },
// { position: 9, name: 'Fluorine', weight: 18.9984, symbol: 'F' },
// { position: 10, name: 'Neon', weight: 20.1797, symbol: 'Ne' },
// { position: 11, name: 'Sodium', weight: 22.9897, symbol: 'Na' },
// { position: 12, name: 'Magnesium', weight: 24.305, symbol: 'Mg' },
// { position: 13, name: 'Aluminum', weight: 26.9815, symbol: 'Al' },
// { position: 14, name: 'Silicon', weight: 28.0855, symbol: 'Si' },
// { position: 15, name: 'Phosphorus', weight: 30.9738, symbol: 'P' },
// { position: 16, name: 'Sulfur', weight: 32.065, symbol: 'S' },
// { position: 17, name: 'Chlorine', weight: 35.453, symbol: 'Cl' },
// { position: 18, name: 'Argon', weight: 39.948, symbol: 'Ar' },
// { position: 19, name: 'Potassium', weight: 39.0983, symbol: 'K' },
// { position: 20, name: 'Calcium', weight: 40.078, symbol: 'Ca' },
